ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
	config.vm.provision "shell", path: "bootstrap-tools.sh"
	config.vm.define "master" do |master|
		master.vm.box = "generic/ubuntu1804"
		master.vm.hostname = "master-node"
		master.vm.network "private_network", ip: "172.42.42.100"
		master.vm.provider :hyperv do |lv|
			lv.memory = 2048
			lv.cpus = 2
		end
		master.vm.provision "shell", path: "bootstrap-master.sh"
	end


	NodeCount = 1
	(1..NodeCount).each do |i|
		config.vm.define "worker-#{i}" do |worker|
			worker.vm.box = "generic/ubuntu1804"
			worker.vm.hostname = "worker-node-#{i}"
			worker.vm.network "private_network", ip: "172.42.42.10#{i}"
			worker.vm.provider :hyperv do |lv|
				lv.memory = 2048
				lv.cpus = 2
			end
			worker.vm.provision "shell", path: "bootstrap-worker.sh"
		end
	end
end
